FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine as build

WORKDIR /tmp
COPY ./Tracker ./Tracker
COPY ./Interfaces ./Interfaces
COPY ./Library ./Library
RUN dotnet restore "./Tracker/Tracker.csproj"

FROM build AS publish
RUN dotnet publish "./Tracker/Tracker.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:3.1-alpine as runtime
RUN apk --no-cache add curl
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Tracker.dll"]