FROM node:16-alpine3.11 as build
WORKDIR /app
COPY ./react-client/package*.json /app/
RUN npm install
COPY ./react-client /app/
RUN npm run build

FROM nginx:1.21 as runtime
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y \
        && apt-get upgrade -y \
        && apt-get install curl -y

COPY --from=build /app/build/ /usr/share/nginx/html
COPY ./react-client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443
ENTRYPOINT ["nginx", "-g", "daemon off;"]