version: "3.7"

services:
    tracker-api:
    #   image: tracker
        build: ./Tracker
        ports:
            - 3000:3000
        volumes:
            - ./Interfaces:/Interface
            - ./Library:/Library