FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine as build

WORKDIR /tmp
COPY ./AnimaAPI ./AnimaAPI
COPY ./Interfaces ./Interfaces
COPY ./Library ./Library
RUN dotnet restore "./AnimaAPI/AnimaAPI.csproj"

FROM build AS publish
RUN dotnet publish "./AnimaAPI/AnimaAPI.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:3.1-alpine as runtime
RUN apk --no-cache add curl
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AnimaAPI.dll"]