version: "3.9"

services:
    tracker-api:
        build: 
            context: .
            dockerfile: Dockerfile.trackerapi
        image: trackerapi:latest
        ports:
            - 4000:80
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/health"]
            interval: 5s
            timeout: 5s
            start_period: 5s
            retries: 5
    
    frontend-api:
        build: 
            context: .
            dockerfile: Dockerfile.frontendapi
        image: frontendapi:latest
        ports:
            - 9422:80
            # - 6001:443
        environment:
        - TRACKER_HOST=tracker-api
        depends_on:
            tracker-api:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/health"]
            interval: 5s
            timeout: 5s
            start_period: 5s
            retries: 5
   
    anima:
        build: 
            context: .
            dockerfile: Dockerfile.backendapi_anima
        image: anima:latest
        ports:
            - 5000:80
        # volumes:
        #     - "C:/_database_:/_database_"
        environment:
        - ANIMA_HOST=anima
        - TRACKER_HOST=tracker-api
        volumes:
            - type: bind
              source: C:/_database_
              target: /_database_
        depends_on:
            tracker-api:
                condition: service_healthy

    mage:
        build: 
            context: .
            dockerfile: Dockerfile.backendapi_mage
        image: mage:latest
        ports:
            - 5001:80
        # volumes:
        #     - "C:/_database_:/_database_"
        environment:
        - MAGE_HOST=mage
        - TRACKER_HOST=tracker-api
        volumes:
            - type: bind
              source: C:/_database_
              target: /_database_
        depends_on:
            tracker-api:
                condition: service_healthy

    client:
        build: 
            context: .
            dockerfile: Dockerfile.client
        image: client:latest
        ports:
            - 10001:80
            - 10002:443
        depends_on:
            frontend-api:
                condition: service_healthy